---
- name: install postgresql repository
  yum:
    name: "{{ PG_PACKAGE_RPM }}"

- name: install postgresql {{ PG_VERSION }} package
  yum:
    name:
      - "{{ PG_PACKAGE_BASE }}-server"
      - "{{ PG_PACKAGE_BASE }}-devel"
      - "{{ PG_PACKAGE_BASE }}-contrib"
  tags: postgresql

- name: detect database cluster
  stat:
    path: "/var/lib/pgsql/{{ PG_VERSION }}/data/PG_VERSION"
  register: dbcluster
  tags: postgresql

- name: setup database cluster
  command: "/usr/pgsql-{{ PG_VERSION }}/bin/{{ PG_PACKAGE_BASE }}-setup initdb"
  when: not dbcluster.stat.exists
  tags: postgresql

- name: copy postgresql conf
  template:
    src: postgresql.conf.j2
    dest: "/var/lib/pgsql/{{ PG_VERSION }}/data/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0600'
  notify: restart postgresql service
  tags: postgresql

- name: start postgresql service
  service:
      name: "postgresql-{{ PG_VERSION }}"
      state: started
      enabled: yes
  tags: postgresql
  when: not dbcluster.stat.exists

- include_tasks: replication.yml
  when: pg_enable_replication and not dbcluster.stat.exists
  tags: postgresql

- include_tasks: keepalived.yml
  when:
    - pg_enable_replication and not dbcluster.stat.exists
    - pg_use_keepalived
  tags: postgresql
