---
- name: setup pacemaker cib
  shell: |
    pcs -f {{ pacemaker_config_file_path }} property set no-quorum-policy="ignore" && \
    pcs -f {{ pacemaker_config_file_path }} property set stonith-enabled="false" && \
    pcs -f {{ pacemaker_config_file_path }} resource create pgsql ocf:heartbeat:pgsql \
       pgctl="/usr/pgsql-{{ PGSQL_VERSION }}/bin/pg_ctl" \
       psql="/usr/pgsql-{{ PGSQL_VERSION }}/bin/psql" \
       pgdata="{{ pgsql_data_dir }}" \
       logfile="{{ pgsql_data_dir }}/startup.log" \
       config="{{ pgsql_data_dir }}/postgresql.conf" \
       tmpdir="/var/run/postgresql" \
       rep_mode="sync" \
       node_list="{{ ansible_play_hosts | join(' ') }}" \
       master_ip="192.168.34.10" \
       repuser="{{ pgsql_replication_user }}" \
       primary_conninfo_opt="keepalives_idle=60 keepalives_interval=5 keepalives_count=5" \
       restore_command="scp 192.168.34.10:{{ pgsql_archive_dir }}/%f %p" \
       stop_escalate="110" \
       \
       op start timeout=120s on-fail=restart \
       op stop timeout=120s on-fail=restart \
       op monitor interval=3s timeout=10s on-fail=restart \
       op monitor interval=2s role=Master timeout=10s on-fail=restart \
       op promote timeout=120s on-fail=block \
       op demote timeout=120s on-fail=restart \
       meta migration-threshold=2 \
       --master clone-max=2 clone-node-max=1 && \
    pcs -f {{ pacemaker_config_file_path }} resource create master-ip ocf:heartbeat:IPaddr2 \
       ip="{{ pacemaker_cluster_info.virtual_ipaddr }}" iflabel="master" \
       op monitor interval=5s && \
    pcs -f {{ pacemaker_config_file_path }} constraint colocation add master-ip \
       with master pgsql-master && \
    pcs -f {{ pacemaker_config_file_path }} constraint order start master-ip \
       then promote pgsql-master && \
    pcs -f {{ pacemaker_config_file_path }} resource create repl-ip ocf:heartbeat:IPaddr2 \
       ip="192.168.34.10" iflabel="repl" \
       op monitor interval=5s && \
    pcs -f {{ pacemaker_config_file_path }} constraint colocation add repl-ip \
       with master pgsql-master && \
    pcs -f {{ pacemaker_config_file_path }} constraint order start repl-ip \
       then promote pgsql-master && \
    pcs -f {{ pacemaker_config_file_path }} constraint location pgsql-master prefers \
       {% for name in ansible_play_hosts %} {{ name }}=0{% endfor %} && \
    pcs -f {{ pacemaker_config_file_path }} constraint location master-ip prefers \
       {% for name in ansible_play_hosts %} {{ name }}=0{% endfor %} && \
    pcs -f {{ pacemaker_config_file_path }} constraint location repl-ip prefers \
       {% for name in ansible_play_hosts %} {{ name }}=0{% endfor %} && \
    pcs cluster cib-push {{ pacemaker_config_file_path }} && \
    pcs cluster cib {{ pacemaker_config_file_path }}
  args:
    creates: "{{ pacemaker_config_file_path }}"

  run_once: true
  delegate_to: "{{ ansible_play_hosts[0] }}"
