---
# - name: create ssh management directry
#  file:
#    path: /var/lib/pgsql/.ssh
#    state: directory
#    owner: postgres
#    group: postgres
#    mode: '0700'
#  tags: postgresql

# - name: generate ssh key
#  openssh_keypair:
#    path: /var/lib/pgsql/.ssh/id_rsa
#    owner: postgres
#    group: postgres
#    mode: '0600'
#  tags: postgresql

# - name: copy public keys file
#  become: yes
#  become_user: postgres
#  command: 'cp /var/lib/pgsql/.ssh/id_rsa.pub /var/lib/pgsql/{{ PG_VERSION }}/data'
#  args:
#    creates: '/var/lib/pgsql/{{ PG_VERSION }}/data/id_rsa.pub'
#  tags: postgresql

- name: create replication user # noqa 301
  become: yes
  become_user: postgres
  command: psql -c "CREATE ROLE {{ pgsql_replication_user }} LOGIN REPLICATION PASSWORD '{{ pgsql_replication_passwd }}';"
  tags: postgresql

- name: set passwd file
  lineinfile:
    path: '/var/lib/pgsql/.pgpass'
    create: yes
    line: '*:*:*:{{ pgsql_replication_user }}:{{ pgsql_replication_passwd }}'
    owner: postgres
    group: postgres
    mode: '0600'
  tags: postgresql

- name: set pg_hba conf
  blockinfile:
    path: '/var/lib/pgsql/{{ PG_VERSION }}/data/pg_hba.conf'
    block: |
      host postgres {{ pgsql_replication_user }} {{ item }} md5
      host replication {{ pgsql_replication_user }} {{ item }} md5
    marker: '# {mark} ANSIBLE MANAGED BLOCK {{ item }}'
    owner: postgres
    group: postgres
    mode: '0600'
  with_items: '{{ pgsql_replication_allow_ipaddr }}'
  tags: postgresql

- name: copy recovery conf template
  template:
    src: recovery.conf.j2
    dest: "/var/lib/pgsql/{{ PG_VERSION }}/data/recovery.conf.in"
    owner: postgres
    group: postgres
    mode: '0600'
  tags: postgresql

- name: copy start shell
  template:
    src: start_replication.sh.j2
    dest: "/usr/local/bin/pg_start_replication.sh"
    owner: root
    group: root
    mode: '0755'
  tags: postgresql

- name: copy join shell
  template:
    src: join_replication.sh.j2
    dest: "/usr/local/bin/pg_join_replication.sh"
    owner: root
    group: root
    mode: '0755'
  tags: postgresql

- name: copy switch sync_state shell
  template:
    src: switch_sync_state.sh.j2
    dest: "/usr/local/bin/pg_switch_sync_state.sh"
    owner: root
    group: root
    mode: '0755'
  tags: postgresql

- name: stop postgresql service
  service:
      name: "postgresql-{{ PG_VERSION }}"
      state: stopped
      enabled: no
  tags: postgresql
