---
- name: restart postgresql service
  service:
    name: "postgresql-{{ PG_VERSION }}"
    state: restarted
  when: not pg_enable_replication
  tags: postgresql

- name: restart keepalived service
  service:
    name: keepalived
    state: restarted
  when: pg_enable_replication
  tags: postgresql
